server:
  port: 8089

# 动态线程池所连Redis管理配置
dynamic:
  thread:
    pool:
      config:
        # 状态；true = 开启、false 关闭
        enabled: true
        # redis host
        host: 127.0.0.1
        # redis port
        port: 6379
        pool-size: 10
        min-idle-size: 5
        idle-timeout: 30000
        connect-timeout: 5000
        retry-attempts: 3
        retry-interval: 1000
        ping-interval: 60000
        keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml


